stages:
  - test
  - package

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

test:
  stage: test
  image: python:3.11-slim
  before_script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install -e .
  script:
    - pytest -v  

.docker-build-job:
  image:
    name: gcr.io/kaniko-project/executor:v1.16.0-debug
    entrypoint: [""]
  before_script:
    - mkdir -p /kaniko/.docker
    - >
      echo "{ \"auths\": {
      \"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n' )\"}
      ,\"https://index.docker.io/v1/\":{\"auth\":\"$(printf "%s:%s" "${DOCKER_HUB_USER}" "${DOCKER_HUB_PASSWORD}" | base64 | tr -d '\n')\"}                   
      }}" > /kaniko/.docker/config.json        

qsynth:grpc-service-publish-docker:
  stage: package
  extends: .docker-build-job
  script:
    - export TAG_VERSION=$(cat pyproject.toml | grep version | awk '{print $3}' | sed 's/"//g')
    - echo "TAG:${TAG_VERSION}"
    - >
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --cache-dir "${CI_KANIKO_CACHE_DIR}/qsynth"            
      --destination="qpointz/qsynth:${TAG_VERSION}"
      --cache=true
  needs:
    - test